services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: the_little_things
    ports: ["3306:3306"]
    volumes: [ "db_data:/var/lib/mysql" ]

  server:
    build: ./server
    depends_on: [ db ]
    environment:
      PORT: 8080
      DB_HOST: db
      DB_NAME: the_little_things
      DB_USER: root
      DB_PASSWORD: rootroot
      CORS_ORIGIN: http://localhost:5173
    ports: ["8080:8080"]
    working_dir: /app
    command: sh -c "npx knex migrate:latest && npx knex seed:run && node server.js"

  client:
    build: ./client
    depends_on: [ server ]
    environment:
      REACT_APP_API_BASE_URL: /api
    ports: ["5173:80"]

volumes:
  db_data:
