/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("todo").del();
  await knex("todo").insert([
    {
      id: 1,
      user_id: 1,
      task: "Complete project",
      category: "Work",
      complete: 0,
      due_at: new Date(2023, 9, 15),
    },
    {
      id: 2,
      user_id: 2,
      task: "Read a book",
      category: "Personal",
      complete: 1,
      due_at: new Date(2023, 10, 10),
    },
    {
      id: 3,
      user_id: 1,
      task: "Attend meeting",
      category: "Work",
      complete: 0,
      due_at: new Date(2023, 9, 30),
    },
    {
      id: 4,
      user_id: 3,
      task: "Exercise",
      category: "Health",
      complete: 1,
      due_at: new Date(2023, 9, 20),
    },
    {
      id: 5,
      user_id: 2,
      task: "Pay bills",
      category: "Finance",
      complete: 0,
      due_at: new Date(2023, 9, 28),
    },
    {
      id: 6,
      user_id: 1,
      task: "Buy groceries",
      category: "Household",
      complete: 0,
      due_at: new Date(2023, 9, 18),
    },
    {
      id: 7,
      user_id: 3,
      task: "Call parents",
      category: "Personal",
      complete: 1,
      due_at: new Date(2023, 10, 5),
    },
    {
      id: 8,
      user_id: 2,
      task: "Prepare presentation",
      category: "Work",
      complete: 0,
      due_at: new Date(2023, 9, 25),
    },
    {
      id: 9,
      user_id: 1,
      task: "Go for a walk",
      category: "Activity",
      complete: 1,
      due_at: new Date(2023, 9, 12),
    },
    {
      id: 10,
      user_id: 3,
      task: "Clean the house",
      category: "Household",
      complete: 0,
      due_at: new Date(2023, 9, 22),
    },
    {
      id: 11,
      user_id: 1,
      task: "Submit report",
      category: "Work",
      complete: 0,
      due_at: new Date(2023, 9, 17),
    },
    {
      id: 12,
      user_id: 1,
      task: "Study for exam",
      category: "Education",
      complete: 0,
      due_at: new Date(2023, 9, 19),
    },
    {
      id: 13,
      user_id: 1,
      task: "Write a blog post",
      category: "Personal",
      complete: 0,
      due_at: new Date(2023, 9, 24),
    },
    {
      id: 14,
      user_id: 1,
      task: "Do laundry",
      category: "Household",
      complete: 0,
      due_at: new Date(2023, 9, 26),
    },
    {
      id: 15,
      user_id: 1,
      task: "Plan a trip",
      category: "Travel",
      complete: 0,
      due_at: new Date(2023, 9, 29),
    },
  ]);
};
