name: CI - Build client & server
on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Client - install and build
        working-directory: client
        run: |
          npm ci
          npm run build

      - name: Server - install (no DB)
        working-directory: server
        run: |
          npm ci
          node -v
